package com.callverse.core.domain.entities;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;
import java.io.Serializable;
import java.util.Objects;
import java.util.UUID;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Composite key of {@link AdvisorSkill}: {@code (advisor_id, skill_id)}.
 *
 * <p>This is one of only two classes in this package that implement {@code equals} and
 * {@code hashCode}, and unlike the entities it has no choice: JPA requires a composite id class to
 * be equal-by-value, because the persistence context uses it as a map key. Entities deliberately go
 * without — see the conventions in {@link AppUser}.
 *
 * <p>Both fields are part of the identity, so both are included, and the implementations are
 * hand-written rather than generated by Lombok: {@code @EqualsAndHashCode} would be correct here
 * today but is the exact annotation the entity convention forbids, and having it appear on one
 * class in the package invites it onto the next.
 */
@Embeddable
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class AdvisorSkillId implements Serializable {

    @Column(name = "advisor_id", nullable = false)
    private UUID advisorId;

    @Column(name = "skill_id", nullable = false)
    private UUID skillId;

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof AdvisorSkillId that)) {
            return false;
        }
        return Objects.equals(advisorId, that.advisorId) && Objects.equals(skillId, that.skillId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(advisorId, skillId);
    }
}
