package com.callverse.core.domain.entities;

import com.callverse.core.domain.enums.UserRole;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import java.util.UUID;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * An authenticated account. Maps {@code app_user}.
 *
 * <p>Exactly one role per account: the schema deliberately has no join table.
 *
 * <p>Not every human in the system has one of these. Simulated customers and simulated advisors
 * have no account at all, which is why {@code customer.user_id} and {@code advisor.user_id} are both
 * nullable. An {@code AppUser} means "someone can log in as this", nothing more.
 *
 * <h2>Mapping conventions used by every entity in this package</h2>
 *
 * <ul>
 *   <li>UUID primary keys are generated by Hibernate ({@code GenerationType.UUID}), not by the
 *       database default. The SQL {@code DEFAULT gen_random_uuid()} remains for direct SQL such as
 *       the seed migration, but letting the database generate would force a read-back per row,
 *       which defeats batching and costs a network round trip on Neon.
 *   <li>{@code TIMESTAMPTZ} maps to {@link Instant}, never {@code OffsetDateTime}: the column stores
 *       a UTC instant and discards the offset, so {@code OffsetDateTime} would advertise
 *       information the column does not carry.
 *   <li>Enums are {@code EnumType.STRING}, never ORDINAL.
 *   <li>Every association is {@code FetchType.LAZY}, including {@code @ManyToOne}, whose JPA default
 *       is EAGER — stated explicitly on each one because the default is the trap.
 *   <li>No {@code equals}/{@code hashCode}. Associations are unidirectional by default, so entities
 *       never enter a Hibernate-managed hash collection, and an id-based {@code equals} becomes a
 *       trap the first time a detached instance is compared to a managed one. Lombok's
 *       {@code @Data} and {@code @EqualsAndHashCode} are never used on entities.
 *   <li>The identifier has no setter. It is assigned once, at persist.
 * </ul>
 */
@Entity
@Table(name = "app_user")
@Getter
@Setter
@NoArgsConstructor
public class AppUser {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false)
    @Setter(AccessLevel.NONE)
    private UUID id;

    @Column(name = "email", nullable = false, unique = true, length = 180)
    private String email;

    /** BCrypt hash. Never the plaintext, and never exposed through any API response. */
    @Column(name = "password_hash", nullable = false, length = 100)
    private String passwordHash;

    @Column(name = "first_name", nullable = false, length = 80)
    private String firstName;

    @Column(name = "last_name", nullable = false, length = 80)
    private String lastName;

    @Enumerated(EnumType.STRING)
    @Column(name = "role", nullable = false, length = 20)
    private UserRole role;

    /** Inactive accounts are excluded from {@code idx_user_role}, which is a partial index. */
    @Column(name = "active", nullable = false)
    private boolean active = true;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt = Instant.now();
}
